Repository google/go-safeweb, pull requests merged in 2020-08, with the labels that each got.

#37 Fixes the gofmt GitHub action according to Michael's tweet ;)
  .github/workflows/main.yaml
Labels: bug

#42 Renamed dispatcher and responsewriter for consistency
  tests/integration/header/header_test.go
  tests/integration/safehtml/safehtml_test.go
Labels: internal cleanup

#63 Improved speed of the test harness for testing net/http parsing by adding a call to runtime.Gosched() before shutting down the server
  internal/requesttesting/test_harness.go
Labels: testing

#66 Form tests cleanup
  safehttp/form_test.go
Labels: internal cleanup

#69 Added integration test which installs the HSTS plugin on a ServeMux and serves a request.
  safehttp/plugins/hsts/hsts.go
  tests/integration/hsts/hsts_test.go
Labels: testing

#83 Added copyright linter to CI so that we don't forget copyright information at the top of source files.
  .github/workflows/copyright_linter.sh
  .github/workflows/main.yaml
  .github/workflows/source-code-copyright-header.txt
  tests/formparams/form_params_test.go
Labels: enhancement

#94 Removed Machinery and prototype.go, refactored tests to use ServeMux instead.
  safehttp/form_test.go
  safehttp/prototype.go
  tests/integration/header/header_test.go
  tests/integration/safehtml/safehtml_test.go
Labels: internal cleanup

#103 Updating tests to reflect that TE identity has been removed in Go1.15
  tests/headers/clte_test.go
Labels: testing

#131 Removed casting in CSP tests that is breaking master
  safehttp/plugins/csp/csp_test.go
Labels: bug, internal cleanup
