Repository google/go-safeweb, pull requests merged in 2020-09, with the labels that each got.

#134 Added set of hashes to CSP plugin
  safehttp/plugins/csp/csp.go
  safehttp/plugins/csp/csp_test.go
Labels: enhancement, plugin

#123 Added token generation to the XSRF plugin.
  go.sum
  safehttp/incoming_request.go
  safehttp/plugins/xsrf/xsrf.go
  safehttp/plugins/xsrf/xsrf_test.go
Labels: enhancement, plugin, v0

#142 Removed unused safehttp.HandleFunc
  safehttp/handler.go
Labels: internal cleanup

#160 Added package level godocs to Collector, CORS, CSP, HSTS, staticheaders and safehttptest.
  safehttp/plugins/collector/collector.go
  safehttp/plugins/cors/cors.go
  safehttp/plugins/csp/csp.go
  safehttp/plugins/hsts/hsts.go
  safehttp/plugins/staticheaders/staticheaders.go
  safehttp/safehttptest/doc.go
Labels: documentation

#167 Cleanup the repository to use DefaultDispatcher in tests and a singe implementation of http.ResponseWriter
  safehttp/default_dispatcher_test.go
  safehttp/mux_test.go
  safehttp/recorder_dispatcher_test.go
  safehttp/response_writer_test.go
  safehttp/safehttptest/recorder.go
  tests/integration/header/header_test.go
  tests/integration/hsts/hsts_test.go
  tests/integration/mux/mux_test.go
  tests/integration/safehtml/safehtml_test.go
  tests/integration/staticheaders/staticheaders_test.go
Labels: internal cleanup, testing

#170 Ensure that all interceptors fullfill the safehttp.Interceptor interface
  safehttp/plugins/cors/cors.go
  safehttp/plugins/cors/cors_test.go
  safehttp/plugins/csp/csp.go
  safehttp/plugins/csp/csp_test.go
  safehttp/plugins/fetch_metadata/fetch_metadata.go
  safehttp/plugins/fetch_metadata/fetch_metadata_test.go
  safehttp/plugins/hsts/hsts.go
  safehttp/plugins/staticheaders/staticheaders.go
  safehttp/plugins/xsrf/xsrf.go
Labels: bug

#175 Add godoc to the Commit function as it is exported
  safehttp/plugins/cors/cors.go
  safehttp/plugins/csp/csp.go
  safehttp/plugins/fetch_metadata/fetch_metadata.go
  safehttp/plugins/hsts/hsts.go
  safehttp/plugins/staticheaders/staticheaders.go
  safehttp/plugins/xsrf/xsrf.go
Labels: documentation

#180 Replace safehttp.Result{} with safehttp.NotWritten() in the repository
  safehttp/mux_test.go
  safehttp/plugins/cors/cors.go
  safehttp/plugins/csp/csp.go
  safehttp/plugins/fetch_metadata/fetch_metadata.go
  safehttp/plugins/hsts/hsts.go
  safehttp/plugins/staticheaders/staticheaders.go
  safehttp/plugins/xsrf/xsrf.go
Labels: internal cleanup

#182 Set the Content-Type header before calling WriteHeader in the safehttp.ResponseWriter
  safehttp/response_writer.go
Labels: bug

#183 Rename the package name of the initial form parameters and query parameters test
  tests/formparams/form_params_test.go
  tests/queryparams/query_params_test.go
Labels: internal cleanup
